;;; oceandsl-mode.el 

;; Package-Requires: ((lsp-mode "6.0"))


;;; Commentary:


;; The main purpose of this mode is to demonstrate how to connect a language
;; server generated by Xtext (http://www.eclipse.org/Xtext/) to Emacs'
;; lsp-mode (https://github.com/emacs-lsp/lsp-mode).

(defconst oceandsl-keywords
  (regexp-opt
   '("configuration" "parameters" "module" "features"))
  "List of keywords of the oconf language.")

(defconst oceandsl-types
  (regexp-opt '("data" "source" "general"))
  "List of standard types of the oconf language.")

(defvar oceandsl-font-lock-keywords
  (list
   (cons oceandsl-keywords 'font-lock-keyword-face)
   (cons oceandsl-types 'font-lock-type-face)))

(defvar oceandsl-ls-jar
  ;; Should be something like "/home/user/bin/org.oceandsl.configuration.ide-1.3.0-SNAPSHOT-ls.jar"
  (expand-file-name "/home/kali/bin/org.oceandsl.configuration.ide-1.3.0-SNAPSHOT-ls.jar"
                    (when load-file-name (file-name-directory load-file-name))))

;;;###autoload
(define-derived-mode oceandsl-mode prog-mode "oceandsl"
  "Major mode for editing OceanDSL files.
The hook `prog-mode-hook' is run during initialization, then
`oceandsl-mode-hook'.
The following keys are set:
\\{oceandsl-mode-map}"
  (setq font-lock-defaults '(oceandsl-font-lock-keywords))
  (setq-local comment-use-syntax t)
  (setq-local comment-start "//")
  (setq-local comment-end "")
  (setq-local comment-start-skip "//+\\s-*"))

;; `oceandsl-mode-syntax-table' is created by the `define-derived-mode' form
;; above, so here we can modify it to teach it about comments.
(modify-syntax-entry ?/   ". 124" oceandsl-mode-syntax-table)
(modify-syntax-entry ?*   ". 23b" oceandsl-mode-syntax-table)
(modify-syntax-entry ?\n  ">" oceandsl-mode-syntax-table)
(modify-syntax-entry ?\^m ">" oceandsl-mode-syntax-table)


;;;###autoload
(add-to-list 'auto-mode-alist '("\\.oconf\\'" . oceandsl-mode))

;;;###autoload
(when (featurep 'lsp-mode)
  ;; https://emacs-lsp.github.io/lsp-mode/page/adding-new-language/
  (add-to-list 'lsp-language-id-configuration
               '(oceandsl-mode . "oceandsl"))
  (lsp-register-client
   (make-lsp-client :major-modes '(oceandsl-mode)
                    :server-id 'oceandsl-ls
                    :new-connection (lsp-stdio-connection (list "java" "-jar" oceandsl-ls-jar)))))

;;;###autoload
;;(when (featurep 'eglot)
  ;; https://github.com/joaotavora/eglot#connecting-to-a-server
;;  (add-to-list 'eglot-server-programs `(oceandsl-mode . ("java" "-jar" ,oceandsl-ls-jar))))

(provide 'oceandsl-mode)